=== JosephLeffler/YouJustLostTheGameAgain/target/classes/story.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

  <xs:element name="map" type="map"/>

  <xs:complexType name="map">
    <xs:all>
      <xs:element name="mapIntro" type="xs:string" minOccurs="0"/>
      <xs:element name="rooms" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="room" type="room" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="characters" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="npc" type="gameNPC"/>
              <xs:element name="player" type="playerCharacter"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="room">
    <xs:all>
      <xs:element name="coordX" type="xs:int"/>
      <xs:element name="coordY" type="xs:int"/>
      <xs:element name="items" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="healingItem" type="healingItem"/>
              <xs:element name="useItem" type="useItem"/>
              <xs:element name="weapon" type="weaponItem"/>
              <xs:element name="armor" type="armorItem"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="roamable" type="xs:boolean"/>
      <xs:element name="shortDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="longDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="exits" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="exit" type="gameExit" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="objects" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="object" type="gameObject" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="healingItem">
    <xs:all>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="shortDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="longDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="amountHealed" type="xs:int"/>
      <xs:element name="uses" type="xs:int"/>
      <xs:element name="boost" type="xs:boolean"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="useItem">
    <xs:all>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="shortDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="longDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="id" type="xs:string" minOccurs="0"/>
      <xs:element name="matchingIds" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="matchingId" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="weaponItem">
    <xs:all>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="shortDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="longDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="slot" type="equipSlot" minOccurs="0"/>
      <xs:element name="damage" type="xs:int"/>
      <xs:element name="piercing" type="xs:int"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="armorItem">
    <xs:all>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="shortDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="longDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="slot" type="equipSlot" minOccurs="0"/>
      <xs:element name="reduction" type="xs:int"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="gameExit">
    <xs:all>
      <xs:element name="id" type="xs:string" minOccurs="0"/>
      <xs:element name="position" type="exitPosition" minOccurs="0"/>
      <xs:element name="locked" type="xs:boolean"/>
      <xs:element name="blocked" type="xs:boolean"/>
      <xs:element name="events" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="event" type="gameEvent" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="gameObject">
    <xs:all>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="id" type="xs:string" minOccurs="0"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="activated" type="xs:boolean"/>
      <xs:element name="requiresItem" type="xs:boolean"/>
      <xs:element name="activationEvent" type="gameEvent" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="gameEvent">
    <xs:all>
      <xs:element name="type" type="eventType" minOccurs="0"/>
      <xs:element name="exitTargetId" type="xs:string" minOccurs="0"/>
      <xs:element name="damageTargetId" type="xs:string" minOccurs="0"/>
      <xs:element name="droppedItems" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="healingItem" type="healingItem"/>
              <xs:element name="useItem" type="useItem"/>
              <xs:element name="weapon" type="weaponItem"/>
              <xs:element name="armor" type="armorItem"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="eventDialogue" type="dialogueLine" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="dialogueLine">
    <xs:all>
      <xs:element name="context" type="lineContext" minOccurs="0"/>
      <xs:element name="text" type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="gameNPC">
    <xs:all>
      <xs:element name="id" type="xs:string" minOccurs="0"/>
      <xs:element name="health" type="xs:int"/>
      <xs:element name="maxHealth" type="xs:int"/>
      <xs:element name="baseDamage" type="xs:int"/>
      <xs:element name="equippedItems" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="weapon" type="weaponItem"/>
              <xs:element name="armor" type="armorItem"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="heldItems" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="healingItem" type="healingItem"/>
              <xs:element name="useItem" type="useItem"/>
              <xs:element name="weapon" type="weaponItem"/>
              <xs:element name="armor" type="armorItem"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="positionX" type="xs:int"/>
      <xs:element name="positionY" type="xs:int"/>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="shortDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="longDescription" type="xs:string" minOccurs="0"/>
      <xs:element name="hostile" type="xs:boolean"/>
      <xs:element name="baseArmor" type="xs:int"/>
      <xs:element name="roaming" type="xs:boolean"/>
      <xs:element name="dialogueLines" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="dialogueLine" type="dialogueLine" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="playerCharacter">
    <xs:all>
      <xs:element name="id" type="xs:string" minOccurs="0"/>
      <xs:element name="health" type="xs:int"/>
      <xs:element name="maxHealth" type="xs:int"/>
      <xs:element name="baseDamage" type="xs:int"/>
      <xs:element name="equippedItems" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="weapon" type="weaponItem"/>
              <xs:element name="armor" type="armorItem"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="heldItems" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="healingItem" type="healingItem"/>
              <xs:element name="useItem" type="useItem"/>
              <xs:element name="weapon" type="weaponItem"/>
              <xs:element name="armor" type="armorItem"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="positionX" type="xs:int"/>
      <xs:element name="positionY" type="xs:int"/>
      <xs:element name="savedGame" type="xs:boolean"/>
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="equipSlot">
    <xs:restriction base="xs:string">
      <xs:enumeration value="HEAD"/>
      <xs:enumeration value="TORSO"/>
      <xs:enumeration value="LEGS"/>
      <xs:enumeration value="HANDS"/>
      <xs:enumeration value="FEET"/>
      <xs:enumeration value="WEAPON"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="exitPosition">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TOP"/>
      <xs:enumeration value="BOTTOM"/>
      <xs:enumeration value="LEFT"/>
      <xs:enumeration value="RIGHT"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="eventType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BLOCK"/>
      <xs:enumeration value="UNBLOCK"/>
      <xs:enumeration value="LOCK"/>
      <xs:enumeration value="UNLOCK"/>
      <xs:enumeration value="DAMAGE"/>
      <xs:enumeration value="END"/>
      <xs:enumeration value="ITEMDROP"/>
      <xs:enumeration value="DIALOGUE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="lineContext">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TALK"/>
      <xs:enumeration value="ATTACK"/>
      <xs:enumeration value="KILL"/>
      <xs:enumeration value="DEATH"/>
      <xs:enumeration value="EVENT"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== JosephLeffler/YouJustLostTheGameAgain/target/test-classes/testStory.xml
<map xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com story.xsd">
	<mapIntro>qwerty</mapIntro>
	<rooms>
		<room>
			<coordX>0</coordX>
			<coordY>0</coordY>
			<shortDescription>Ah</shortDescription>
			<longDescription>Aaaah</longDescription>
			<roamable>false</roamable>
			<items>
				<weapon>
					<name>Sword</name>
					<shortDescription>Hm</shortDescription>
					<longDescription>Hmmmmmm</longDescription>
					<damage>10</damage>
					<piercing>0</piercing>
					<slot>WEAPON</slot>
				</weapon>
				<armor>
					<name>Helm</name>
					<shortDescription>No</shortDescription>
					<longDescription>Nooooooo</longDescription>
					<reduction>15</reduction>
					<slot>HEAD</slot>
				</armor>
				<armor>
					<name>Steel Plate Armor</name>
					<shortDescription>Grr</shortDescription>
					<longDescription>Grrrrrr</longDescription>
					<reduction>35</reduction>
					<slot>TORSO</slot>
				</armor>
				<armor>
					<name>Leather Chaps</name>
					<shortDescription>Lol</shortDescription>
					<longDescription>Loooool</longDescription>
					<reduction>10</reduction>
					<slot>LEGS</slot>
				</armor>
				<armor>
					<name>Mittens</name>
					<shortDescription>Mittens</shortDescription>
					<longDescription>No, that's not the name of a cat. They're actual mittens, dimwit.</longDescription>
					<reduction>5</reduction>
					<slot>HANDS</slot>
				</armor>
				<armor>
					<name>Uggs</name>
					<shortDescription>Ugh</shortDescription>
					<longDescription>Uuuuuugh</longDescription>
					<reduction>0</reduction>
					<slot>FEET</slot>
				</armor>
				<useItem>
					<id>Key1</id>
					<shortDescription>asdf</shortDescription>
					<longDescription>asdfghjkl</longDescription>
					<name>New Key</name>
					<matchingIds>
						<matchingId>Chest1</matchingId>
					</matchingIds>
				</useItem>
			</items>
			<objects>
				<object>
					<name>Chest</name>
					<id>Chest1</id>
					<requiresItem>true</requiresItem>
					<activated>false</activated>
					<description>A chest.</description>
					<activationEvent>
						<type>ITEMDROP</type>
						<droppedItems>
							<useItem>
								<id>Key2</id>
								<shortDescription>Why</shortDescription>
								<longDescription>Why did I make every single item need a description?</longDescription>
								<name>Old Key</name>
								<matchingIds>
									<matchingId>Door1</matchingId>
								</matchingIds>
							</useItem>
						</droppedItems>
					</activationEvent>
				</object>
				<object>
					<name>Chair</name>
					<id>Chair</id>
					<requiresItem>false</requiresItem>
					<activated>false</activated>
					<activationEvent>
						<type>DIALOGUE</type>
						<eventDialogue>
							<context>EVENT</context>
							<text>You sit down. The chair breaks.</text>
						</eventDialogue>
					</activationEvent>
				</object>
			</objects>
			<exits>
				<exit>
					<id>Door1</id>
					<position>TOP</position>
					<blocked>false</blocked>
					<locked>true</locked>
					<events>
						<event>
							<type>UNLOCK</type>
							<eventDialogue>
								<context>EVENT</context>
								<text>You unlock the door.</text>
							</eventDialogue>
						</event>
					</events>
				</exit>
				<exit>
					<id>Door2</id>
					<position>BOTTOM</position>
					<blocked>true</blocked>
					<locked>false</locked>
					<events>
						<event>
							<type>UNBLOCK</type>
							<eventDialogue>
								<context>EVENT</context>
								<text>You remove the rubble from in front of the door.</text>
							</eventDialogue>
						</event>
					</events>
				</exit>
				<exit>
					<id>Door3</id>
					<position>RIGHT</position>
					<blocked>false</blocked>
					<locked>false</locked>
				</exit>
			</exits>
		</room>
	</rooms>
	<characters>
		<player>
			<id>player</id>
			<health>100</health>
			<maxHealth>100</maxHealth>
			<baseDamage>5</baseDamage>
			<positionX>0</positionX>
			<positionY>0</positionY>
			<savedGame>false</savedGame>
			<heldItems>
				<weapon>
					<name>Rapier</name>
					<shortDescription>Brr</shortDescription>
					<longDescription>Brrrrrr</longDescription>
					<damage>5</damage>
					<piercing>5</piercing>
					<slot>WEAPON</slot>
				</weapon>
				<healingItem>
					<name>Potion</name>
					<shortDescription>Rr</shortDescription>
					<longDescription>Rrrrrr</longDescription>
					<boost>false</boost>
					<uses>2</uses>
					<amountHealed>25</amountHealed>
				</healingItem>
			</heldItems>
			<equippedItems>
				<weapon>
					<name>Sword</name>
					<shortDescription>Hm</shortDescription>
					<longDescription>Hmmmmmm</longDescription>
					<damage>10</damage>
					<piercing>0</piercing>
					<slot>WEAPON</slot>
				</weapon>
				<armor>
					<name>Helm</name>
					<shortDescription>No</shortDescription>
					<longDescription>Nooooooo</longDescription>
					<reduction>15</reduction>
					<slot>HEAD</slot>
				</armor>
				<armor>
					<name>Steel Plate Armor</name>
					<shortDescription>Grr</shortDescription>
					<longDescription>Grrrrrr</longDescription>
					<reduction>35</reduction>
					<slot>TORSO</slot>
				</armor>
				<armor>
					<name>Leather Chaps</name>
					<shortDescription>Lol</shortDescription>
					<longDescription>Loooool</longDescription>
					<reduction>10</reduction>
					<slot>LEGS</slot>
				</armor>
			</equippedItems>
		</player>
		<npc>
			<name>Grue</name>
			<id>Grue1</id>
			<health>25</health>
			<maxHealth>25</maxHealth>
			<baseArmor>5</baseArmor>
			<baseDamage>10</baseDamage>
			<hostile>true</hostile>
			<shortDescription>A grue.</shortDescription>
			<longDescription>A grue. They tend to like dark places.</longDescription>
			<positionX>0</positionX>
			<positionY>0</positionY>
			<roaming>false</roaming>
			<heldItems>
				<armor>
					<name>Mittens</name>
					<shortDescription>Mittens</shortDescription>
					<longDescription>No, that's not the name of a cat. They're actual mittens, dimwit.</longDescription>
					<reduction>5</reduction>
					<slot>HANDS</slot>
				</armor>
			</heldItems>
			<equippedItems>
				<armor>
					<name>Uggs</name>
					<shortDescription>Ugh</shortDescription>
					<longDescription>Uuuuuugh</longDescription>
					<reduction>0</reduction>
					<slot>FEET</slot>
				</armor>
			</equippedItems>
		</npc>
		<npc>
			<name>Goblin</name>
			<id>Goblin1</id>
			<health>10</health>
			<maxHealth>10</maxHealth>
			<baseArmor>0</baseArmor>
			<baseDamage>5</baseDamage>
			<hostile>true</hostile>
			<shortDescription>A goblin.</shortDescription>
			<longDescription>A goblin. The weakest of monsters.</longDescription>
			<positionX>0</positionX>
			<positionY>0</positionY>
			<roaming>true</roaming>
		</npc>
		<npc>
			<name>Farmer</name>
			<id>Farmer1</id>
			<health>10</health>
			<maxHealth>10</maxHealth>
			<baseArmor>0</baseArmor>
			<baseDamage>5</baseDamage>
			<hostile>false</hostile>
			<shortDescription>A farmer.</shortDescription>
			<longDescription>A farmer. Not sure what he's doing here.</longDescription>
			<positionX>0</positionX>
			<positionY>0</positionY>
			<roaming>false</roaming>
			<dialogueLines>
				<dialogueLine>
					<context>TALK</context>
					<text>Howdy there.</text>
				</dialogueLine>
				<dialogueLine>
					<context>KILL</context>
					<text>Why'd ya have ta go and fight me? I didn't want ta hurt ya.</text>
				</dialogueLine>
				<dialogueLine>
					<context>DEATH</context>
					<text>*gurgle*</text>
				</dialogueLine>
				<dialogueLine>
					<context>TALK</context>
					<text>Top of the mornin' to ya.</text>
				</dialogueLine>
			</dialogueLines>
		</npc>
	</characters>
</map>

=== JosephLeffler/YouJustLostTheGameAgain/YouJustLostTheGameAgain/resources/story.xml
<map xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com story.xsd">
	<mapIntro>asdf</mapIntro>
	<rooms>
		<room>
			<coordX>0</coordX>
			<coordY>0</coordY>
			<items>
				<weapon>
					<name>Sword</name>
					<shortDescription>A sword</shortDescription>
					<longDescription>A shiny new sword. Pretty basic.</longDescription>
					<slot>WEAPON</slot>
					<damage>10</damage>
					<piercing>0</piercing>
				</weapon>
			</items>
			<roamable>false</roamable>
			<shortDescription>A room with no way out</shortDescription>
			<longDescription>A plain white room with one chair and no way out.</longDescription>
			<objects>
				<object>
					<id>chair</id>
					<description>a plain brown wooden chair</description>
					<activated>false</activated>
					<requiresItem>false</requiresItem>
					<activationEvent>
						<type>END</type>
						<eventDialogue>
							<context>EVENT</context>
							<text>You sit in the chair and wait for all eternity. The End.</text>
						</eventDialogue>
					</activationEvent>
				</object>
			</objects>
			<exits>
				<exit>
					<id>wall1</id>
					<position>TOP</position>
					<blocked>true</blocked>
					<locked>false</locked>
				</exit>
			</exits>
		</room>
	</rooms>
	<characters>
		<player>
			<id>player</id>
			<health>100</health>
			<baseDamage>1</baseDamage>
			<equippedItems>
				<weapon>
					<name>Fisticuffs</name>
					<shortDescription>Your fists.</shortDescription>
					<longDescription>Fisticuffs. A brutish weapon for a less civilized age.</longDescription>
					<slot>WEAPON</slot>
					<damage>2</damage>
					<piercing>0</piercing>
				</weapon>
				<armor>
					<name>Helm of the Ancients</name>
					<shortDescription>An ancient helmet.</shortDescription>
					<longDescription>An old, rusty, broken helmet. Just because it's ancient doesn't mean it's good.</longDescription>
					<slot>HEAD</slot>
					<reduction>5</reduction>
				</armor>
			</equippedItems>
			<heldItems>
				<healingItem>
					<name>Health Potion</name>
					<shortDescription>A health potion.</shortDescription>
					<longDescription>Restores 20 health.</longDescription>
					<amountHealed>20</amountHealed>
					<uses>3</uses>
					<boost>false</boost>
				</healingItem>
				<useItem>
					<name>A key</name>
					<shortDescription>A rusty key.</shortDescription>
					<longDescription>An old rusty key. It might fit something, but it looks like it's about to break.</longDescription>
					<id>key1</id>
					<matchingIds>
						<matchingId>door1</matchingId>
					</matchingIds>
				</useItem>
			</heldItems>
			<positionX>0</positionX>
			<positionY>0</positionY>
			<savedGame>false</savedGame>
		</player>
	</characters>
</map>
